# Configurando a conex\u00e3o com MongoDB enquanto reposit\u00f3rio de dados
spring.data.mongodb.uri=mongodb+srv://thindesk_sy:Dubstep1067@thindesk.dxcgt8t.mongodb.net/?appName=thindesk
spring.data.mongodb.database=thindesk_sy
spring.data.mongodb.auto-index-creation=true

#thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

#Log
logging.level.com.pfc=DEBUG